"""
ingest_patterns.py  (shared_rag/kb_ingest)
───────────────────────────────────────────
Seeds the L3_typologies ChromaDB collection with fraud pattern typologies.
Moved from et_service/monitoring_agent/rag/kb_ingest/ingest_patterns.py.

Key fix applied here:
  [FIX-1] L3 embeddings are generated by encode_flags_for_l3()
           (256-d signal-sequence projection), NOT by SentenceTransformer.
           The rag_layer queries L3 with signal vectors — both sides
           must use the same encoder.
  [FIX-2] Each typology defines representative 'signals' list that maps
           to known anomaly_flag_labels for accurate encoding.

Run before any agent goes live:
  python -m et_service.shared_rag.kb_ingest.ingest_patterns

Idempotent — uses upsert.
"""

import sys
import os

_SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, '..', '..', '..', '..'))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from et_service.shared_rag.vector_store import (
    upsert_vector_documents, collection_count, COLLECTIONS
)
from et_service.shared_rag.encoders import encode_flags_for_l3  # [FIX-1]

# Each typology's 'signals' list uses exact anomaly flag label prefixes
# as defined in anomaly_extractor.py — this ensures the signal vector
# maps to the same projection space used at query time.

TYPOLOGIES = [
    {
        "id": "TYPO-001-ACCOUNT-TAKEOVER",
        "text": (
            "Account Takeover (ATO): An attacker gains unauthorised access to "
            "a legitimate customer's account through phishing, credential stuffing, "
            "or SIM swapping. Key indicators: transactions at unusual hours, "
            "large payments to new recipients, velocity burst, high z-score."
            "Risk: CRITICAL."
        ),
        # [FIX-1] Representative flag labels for this typology
        "signals": [
            "UNUSUAL_HOUR",
            "LATE_NIGHT_TRANSACTION",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "HIGH_RISK_COMPOSITE: large_amount + new_recipient",
            "HIGH_RISK_COMPOSITE: late_night + new_recipient",
            "EXTREME_AMOUNT_DEVIATION",
            "VELOCITY_BURST",
        ],
        "metadata": {
            "typology": "account_takeover",
            "key_signals": "unusual_hour,new_recipient,velocity_burst,high_z_score",
            "risk_level": "CRITICAL",
            "base_risk_score": "85",
        },
    },
    {
        "id": "TYPO-002-STRUCTURING-SMURFING",
        "text": (
            "Structuring / Smurfing: Deliberately breaking a large transaction "
            "into multiple smaller ones to avoid regulatory reporting thresholds. "
            "Key indicators: amounts just below Rs 10,000 or Rs 50,000 thresholds, "
            "multiple new recipients, exceeding daily volume, round amounts. "
            "Risk: HIGH. Regulatory reporting required."
        ),
        "signals": [
            "STRUCTURING_SIGNAL_NEAR_THRESHOLD",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "EXCEEDS_DAILY_VOLUME_THRESHOLD",
            "ROUND_NUMBER_AMOUNT",
            "HIGH_DAILY_FREQUENCY",
        ],
        "metadata": {
            "typology": "structuring",
            "key_signals": "near_threshold,multiple_recipients,daily_volume_exceeded",
            "risk_level": "HIGH",
            "base_risk_score": "70",
        },
    },
    {
        "id": "TYPO-003-MONEY-MULE",
        "text": (
            "Money Mule: An account used as an intermediary to launder illicit funds. "
            "Key indicators: dormant account suddenly reactivated, cold start profile, "
            "large deposits followed by immediate large withdrawals, new recipients. "
            "Risk: CRITICAL. Law enforcement referral required."
        ),
        "signals": [
            "LARGE_AMOUNT_10X_AVERAGE",
            "EXCEEDS_PERSONAL_MAX",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "HIGH_RISK_COMPOSITE: large_amount + new_recipient",
            "EXCEEDS_DAILY_VOLUME_THRESHOLD",
        ],
        "metadata": {
            "typology": "money_mule",
            "key_signals": "cold_start,large_amount,rapid_movement,new_recipient",
            "risk_level": "CRITICAL",
            "base_risk_score": "85",
        },
    },
    {
        "id": "TYPO-004-VELOCITY-ATTACK",
        "text": (
            "Velocity Attack: Automated or semi-automated execution of multiple "
            "transactions in rapid succession. Key indicators: more than 3 transactions "
            "within 1 hour (velocity burst), multiple new recipients, small individual "
            "amounts but large aggregate, may occur at unusual hours. "
            "Risk: HIGH. Account lock recommended immediately."
        ),
        "signals": [
            "VELOCITY_BURST",
            "HIGH_DAILY_FREQUENCY",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "UNUSUAL_HOUR",
            "EXCEEDS_DAILY_VOLUME_THRESHOLD",
        ],
        "metadata": {
            "typology": "velocity_attack",
            "key_signals": "velocity_burst,multiple_new_recipients,unusual_hour",
            "risk_level": "HIGH",
            "base_risk_score": "70",
        },
    },
    {
        "id": "TYPO-005-SOCIAL-ENGINEERING",
        "text": (
            "Social Engineering / Phishing-Induced Transfer: Customer is manipulated "
            "into voluntarily initiating a payment to a fraudster. Key indicators: "
            "single large transfer to new recipient, amount significantly above average, "
            "may occur during normal hours. "
            "Risk: MEDIUM-HIGH."
        ),
        "signals": [
            "HIGH_AMOUNT_DEVIATION",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "HIGH_RISK_COMPOSITE: large_amount + new_recipient",
            "EXCEEDS_PERSONAL_MAX",
        ],
        "metadata": {
            "typology": "social_engineering",
            "key_signals": "new_recipient,high_z_score,large_amount",
            "risk_level": "MEDIUM-HIGH",
            "base_risk_score": "62",
        },
    },
    {
        "id": "TYPO-006-FIRST-PARTY-FRAUD",
        "text": (
            "First-Party Fraud: The account holder commits fraud, typically "
            "by depositing then transferring funds and disputing the deposit. "
            "Key indicators: new account, large deposit then immediate large withdrawal, "
            "amount near regulatory thresholds, single new recipient. "
            "Risk: HIGH."
        ),
        "signals": [
            "STRUCTURING_SIGNAL_NEAR_THRESHOLD",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "LARGE_AMOUNT_10X_AVERAGE",
            "HIGH_RISK_COMPOSITE: large_amount + new_recipient",
        ],
        "metadata": {
            "typology": "first_party_fraud",
            "key_signals": "cold_start,large_amount,near_threshold,new_recipient",
            "risk_level": "HIGH",
            "base_risk_score": "70",
        },
    },
    {
        "id": "TYPO-007-DORMANT-EXPLOITATION",
        "text": (
            "Dormant Account Exploitation: A rarely-used account suddenly shows "
            "high-value activity. Key indicators: no prior activity then sudden burst, "
            "large amounts relative to history, transfers to unfamiliar recipients, "
            "unusual hours. Risk: HIGH."
        ),
        "signals": [
            "LARGE_AMOUNT_10X_AVERAGE",
            "EXCEEDS_PERSONAL_MAX",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "UNUSUAL_HOUR",
            "EXCEEDS_DAILY_VOLUME_THRESHOLD",
        ],
        "metadata": {
            "typology": "dormant_exploitation",
            "key_signals": "cold_start,large_amount,new_recipient,unusual_hour",
            "risk_level": "HIGH",
            "base_risk_score": "70",
        },
    },
    {
        "id": "TYPO-008-ROUND-TRIPPING",
        "text": (
            "Round-Tripping / Layering: Funds circulated through multiple accounts "
            "to obscure origin. Key indicators: repeated transactions of identical "
            "amounts, round numbers, high daily frequency, new recipients who "
            "subsequently become senders. Risk: HIGH. AML investigation required."
        ),
        "signals": [
            "ROUND_NUMBER_AMOUNT",
            "HIGH_DAILY_FREQUENCY",
            "NEW_RECIPIENT_NEVER_TRANSACTED",
            "VELOCITY_BURST",
            "STRUCTURING_SIGNAL_NEAR_THRESHOLD",
        ],
        "metadata": {
            "typology": "round_tripping",
            "key_signals": "round_number,high_frequency,new_recipients",
            "risk_level": "HIGH",
            "base_risk_score": "70",
        },
    },
]


def ingest():
    """Seeds the L3_typologies collection with fraud typology patterns."""
    collection_name = COLLECTIONS['L3']

    ids       = [t['id'] for t in TYPOLOGIES]
    documents = [t['text'] for t in TYPOLOGIES]
    metadatas = [t['metadata'] for t in TYPOLOGIES]

    # [FIX-1] Generate signal-sequence embeddings using encode_flags_for_l3
    # (256-d bootstrap projection). Same encoder used by rag_layer at query time.
    embeddings = [encode_flags_for_l3(t['signals']) for t in TYPOLOGIES]

    upsert_vector_documents(collection_name, ids, embeddings, documents, metadatas)
    count = collection_count(collection_name)
    print(f"[OK] L3_typologies seeded with {count} fraud typology patterns.")


if __name__ == '__main__':
    ingest()
