"""
STR Assembler — Generates Suspicious Transaction Reports

Assembles STR content from fraud_cases, alert data, and citations.
Produces a structured JSON STR document for regulatory filing.
"""

import json
from datetime import datetime
from typing import Dict, Any, List, Optional
from et_service.cla.constants import (
    STR_TEMPLATE,
    CTR_TEMPLATE,
    get_severity_from_score,
    TYPOLOGY_CODES
)
from et_dao.cla_dao import get_citation_by_id


def assemble_str(
    case_data: Dict[str, Any],
    alert_data: Dict[str, Any],
    transaction_data: Dict[str, Any],
    customer_data: Dict[str, Any],
    citation_ids: List[str]
) -> Dict[str, Any]:
    """
    Assembles a complete STR document from case and alert data.

    Args:
        case_data: fraud_cases row
        alert_data: fraud_alerts row
        transaction_data: transactions row
        customer_data: customers row
        citation_ids: List of citation IDs to include

    Returns:
        STR document dict
    """
    try:
        # Extract key fields
        filing_id = case_data.get('case_id', '').replace('CASE-', 'STR-')
        case_id = case_data['case_id']
        customer_id = customer_data['customer_id']
        customer_name = customer_data['full_name']
        account_number = customer_data['account_number']

        transaction_id = transaction_data['transaction_id']
        transaction_date = transaction_data['created_at'].isoformat() if hasattr(transaction_data['created_at'], 'isoformat') else str(transaction_data['created_at'])
        amount = float(transaction_data['amount'])
        description = transaction_data.get('description', 'N/A')

        # Determine severity from RAA score
        final_raa_score = float(alert_data.get('final_raa_score', 0))
        severity = get_severity_from_score(final_raa_score)

        # Extract typology code
        typology_code = alert_data.get('typology_code', 'TY-999')

        # Build narrative
        narrative = _build_narrative(
            case_data=case_data,
            alert_data=alert_data,
            transaction_data=transaction_data,
            customer_data=customer_data
        )

        # Fetch citation details
        citations = []
        for cit_id in citation_ids:
            citation = get_citation_by_id(cit_id)
            if citation:
                citations.append({
                    'citation_id': cit_id,
                    'category': citation['category'],
                    'title': citation['title'],
                    'content': citation['content'][:200]  # truncate for STR
                })

        # Investigation note
        investigation_note = alert_data.get('investigation_note', 'Auto-generated by EagleTrust CLA')

        # Assemble STR document
        str_document = {
            **STR_TEMPLATE,
            'filing_id': filing_id,
            'case_id': case_id,
            'customer_id': customer_id,
            'customer_name': customer_name,
            'account_number': account_number,
            'transaction_id': transaction_id,
            'transaction_date': transaction_date,
            'amount': amount,
            'description': description,
            'severity': severity,
            'typology_code': typology_code,
            'typology_description': TYPOLOGY_CODES.get(typology_code, 'Suspicious Activity'),
            'narrative': narrative,
            'citations': citations,
            'investigation_note': investigation_note,
            'final_raa_score': final_raa_score,
            'generated_at': datetime.utcnow().isoformat()
        }

        return str_document

    except Exception as e:
        print(f"[str_assembler] Error assembling STR: {e}")
        return {}


def assemble_ctr(
    transaction_data: Dict[str, Any],
    customer_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Assembles a CTR (Cash Transaction Report) document.

    Args:
        transaction_data: transactions row
        customer_data: customers row

    Returns:
        CTR document dict
    """
    try:
        filing_id = f"CTR-{transaction_data['transaction_id']}"
        customer_id = customer_data['customer_id']
        customer_name = customer_data['full_name']
        account_number = customer_data['account_number']

        transaction_id = transaction_data['transaction_id']
        transaction_date = transaction_data['created_at'].isoformat() if hasattr(transaction_data['created_at'], 'isoformat') else str(transaction_data['created_at'])
        amount = float(transaction_data['amount'])
        description = transaction_data.get('description', 'High-value transaction')

        # Build simple narrative for CTR
        narrative = (
            f"High-value transaction of ₹{amount:,.2f} detected for customer {customer_id}. "
            f"Transaction exceeds CTR threshold of ₹{CTR_TEMPLATE['threshold_amount']:,.2f}. "
            f"Auto-filed for compliance review."
        )

        ctr_document = {
            **CTR_TEMPLATE,
            'filing_id': filing_id,
            'customer_id': customer_id,
            'customer_name': customer_name,
            'account_number': account_number,
            'transaction_id': transaction_id,
            'transaction_date': transaction_date,
            'amount': amount,
            'description': description,
            'narrative': narrative,
            'generated_at': datetime.utcnow().isoformat()
        }

        return ctr_document

    except Exception as e:
        print(f"[str_assembler] Error assembling CTR: {e}")
        return {}


def _build_narrative(
    case_data: Dict[str, Any],
    alert_data: Dict[str, Any],
    transaction_data: Dict[str, Any],
    customer_data: Dict[str, Any]
) -> str:
    """
    Builds a human-readable narrative for the STR filing.
    """
    try:
        # Extract key fields
        customer_id = customer_data['customer_id']
        customer_name = customer_data['full_name']
        account_number = customer_data['account_number']

        transaction_id = transaction_data['transaction_id']
        amount = float(transaction_data['amount'])
        description = transaction_data.get('description', 'N/A')

        final_raa_score = float(alert_data.get('final_raa_score', 0))
        raa_verdict = alert_data.get('raa_verdict', 'UNKNOWN')
        typology_code = alert_data.get('typology_code', 'TY-999')

        # Evidence pack from case
        evidence_pack = case_data.get('evidence_pack', {})
        anomaly_flags = evidence_pack.get('anomaly_flags', {})
        pattern_types = evidence_pack.get('pattern_types', [])

        # Build narrative sections
        narrative_parts = []

        # Section 1: Transaction Summary
        narrative_parts.append(
            f"On {transaction_data['created_at'].strftime('%Y-%m-%d %H:%M:%S') if hasattr(transaction_data['created_at'], 'strftime') else transaction_data['created_at']}, "
            f"customer {customer_id} ({customer_name}) executed a transaction of ₹{amount:,.2f} "
            f"from account {account_number}. Transaction ID: {transaction_id}."
        )

        # Section 2: Alert Details
        narrative_parts.append(
            f"The EagleTrust Fraud Detection System flagged this transaction with a Risk Assessment Score of {final_raa_score:.2f}/100, "
            f"resulting in a verdict of {raa_verdict}. The transaction was classified under typology {typology_code} ({TYPOLOGY_CODES.get(typology_code, 'Unknown')})."
        )

        # Section 3: Anomaly Indicators
        if anomaly_flags:
            anomaly_descriptions = []
            for flag, value in anomaly_flags.items():
                if value:
                    anomaly_descriptions.append(flag.replace('_', ' ').title())
            if anomaly_descriptions:
                narrative_parts.append(
                    f"Anomaly indicators detected: {', '.join(anomaly_descriptions)}."
                )

        # Section 4: Pattern Analysis
        if pattern_types:
            narrative_parts.append(
                f"Pattern analysis identified the following behavioral patterns: {', '.join(pattern_types)}."
            )

        # Section 5: Regulatory Action
        narrative_parts.append(
            f"Based on the multi-agent analysis, this transaction is being reported as suspicious activity "
            f"in compliance with FIU-IND guidelines and the Prevention of Money Laundering Act (PMLA) 2002."
        )

        return ' '.join(narrative_parts)

    except Exception as e:
        print(f"[str_assembler] Error building narrative: {e}")
        return "Error generating narrative. Manual review required."


def validate_str_document(str_document: Dict[str, Any]) -> bool:
    """
    Validates that an STR document has all required fields.
    Returns True if valid, False otherwise.
    """
    required_fields = STR_TEMPLATE['fields']
    for field in required_fields:
        if field not in str_document:
            print(f"[str_assembler] Missing required field: {field}")
            return False
    return True


def validate_ctr_document(ctr_document: Dict[str, Any]) -> bool:
    """
    Validates that a CTR document has all required fields.
    Returns True if valid, False otherwise.
    """
    required_fields = CTR_TEMPLATE['fields']
    for field in required_fields:
        if field not in ctr_document:
            print(f"[str_assembler] Missing required field: {field}")
            return False
    return True
