"""
ingest_cases.py
───────────────
One-time script to seed the L2_fraud_cases ChromaDB collection
with synthetic historical fraud case documents.

Each case describes a real-world fraud pattern with signals,
amounts, and outcomes — enabling the RAG layer to find similar
past cases when evaluating new transactions.

Run before TMA goes live:
  python -m et_service.monitoring_agent.rag.kb_ingest.ingest_cases

Idempotent — uses upsert, safe to run multiple times.

Key fix applied here:
  [FIX-1] L2 embeddings are generated by encode_features_for_l2()
           (128-d bootstrap projection of the 15 anomaly features),
           NOT by SentenceTransformer (384-d text embeddings).
           The rag_layer queries L2 with feature vectors — both sides
           must use the same encoder / projection space.
  [FIX-2] Each case now carries 'confirmed_risk_score' in metadata
           so that rag_layer._score_l2() can compute the
           similarity-weighted average correctly.
"""

import sys
import os

_SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, '..', '..', '..', '..'))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from et_service.monitoring_agent.rag.vector_store import (
    upsert_vector_documents, collection_count, COLLECTIONS
)
from et_service.monitoring_agent.rag.encoders import encode_features_for_l2   # [FIX-1]

# ── Historical fraud cases ────────────────────────────────────────────────────
# Synthetic seed data covering key fraud typologies.
# The feedback_writer will add real confirmed cases over time.
#
# Each entry has:
#   text     — human-readable document stored alongside the vector (for debug)
#   features — representative 15-feature values for this pattern.
#              These are encoded by encode_features_for_l2() to produce the
#              128-d search vector. Use the same feature names as FEATURE_NAMES.
#   metadata — ChromaDB metadata (all values must be strings or ints/floats)
#              'confirmed_risk_score' is required by rag_layer._score_l2()

FRAUD_CASES = [
    {
        "id": "CASE-001-ATO",
        "text": (
            "Account Takeover — Confirmed Fraud. Customer account compromised "
            "via phishing. Attacker initiated Rs 48,000 transfer at 03:15 AM "
            "to unknown recipient. Amount z-score was 4.1, exceeding personal "
            "maximum by 2.3x. Late night transaction to new recipient. "
            "Velocity: 4 transactions in 45 minutes draining the account. "
            "Outcome: Funds frozen, reversal successful."
        ),
        # [FIX-1] Representative feature values for this pattern
        "features": {
            "amount_z_score": 4.1,  "amount_vs_max": 2.3,
            "exceeds_daily_volume": 1, "is_large_amount": 1,
            "is_near_threshold": 0, "is_round_number": 0,
            "is_unusual_hour": 1, "hour_sin": 0.131, "hour_cos": -0.991,
            "is_new_recipient": 1, "transactions_last_1h": 4,
            "transactions_last_24h": 5, "is_velocity_burst": 1,
            "high_z_new_recipient": 1, "late_night_new_recipient": 1,
        },
        "metadata": {
            "pattern": "account_takeover",
            "amount_range": "40000-50000",
            "signals": "late_night,new_recipient,velocity_burst,high_z_score",
            "outcome": "confirmed_fraud",
            "severity": "CRITICAL",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
    {
        "id": "CASE-002-STRUCTURING",
        "text": (
            "Structuring — Confirmed Suspicious Activity. Customer made 6 "
            "transactions of Rs 9,500 to Rs 9,950 each within 3 days, all "
            "to different recipients. Each amount deliberately below the "
            "Rs 10,000 reporting threshold. Total moved: Rs 58,200. "
            "Classic smurfing pattern. Outcome: STR filed with FIU-IND."
        ),
        "features": {
            "amount_z_score": 0.3,  "amount_vs_max": 0.6,
            "exceeds_daily_volume": 1, "is_large_amount": 0,
            "is_near_threshold": 1, "is_round_number": 0,
            "is_unusual_hour": 0, "hour_sin": 0.866, "hour_cos": 0.5,
            "is_new_recipient": 1, "transactions_last_1h": 2,
            "transactions_last_24h": 6, "is_velocity_burst": 0,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "structuring",
            "amount_range": "9000-9999",
            "signals": "near_threshold,multiple_new_recipients,daily_volume_exceeded",
            "outcome": "confirmed_suspicious",
            "severity": "HIGH",
            "confirmed_risk_score": "65",   # [FIX-2]
        },
    },
    {
        "id": "CASE-003-MULE",
        "text": (
            "Money Mule — Confirmed Fraud. Dormant savings account reactivated "
            "after 8 months of inactivity. Received Rs 2,00,000 credit followed "
            "by immediate Rs 1,95,000 debit to an unfamiliar account within "
            "20 minutes. Cold start profile, no established transaction pattern. "
            "Outcome: Account frozen, investigation revealed mule recruitment."
        ),
        "features": {
            "amount_z_score": 5.0,  "amount_vs_max": 3.5,
            "exceeds_daily_volume": 1, "is_large_amount": 1,
            "is_near_threshold": 0, "is_round_number": 1,
            "is_unusual_hour": 0, "hour_sin": 0.5, "hour_cos": 0.866,
            "is_new_recipient": 1, "transactions_last_1h": 2,
            "transactions_last_24h": 2, "is_velocity_burst": 0,
            "high_z_new_recipient": 1, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "money_mule",
            "amount_range": "100000-200000",
            "signals": "cold_start,large_amount,new_recipient,rapid_movement",
            "outcome": "confirmed_fraud",
            "severity": "CRITICAL",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
    {
        "id": "CASE-004-FIRST-PARTY",
        "text": (
            "First-Party Fraud — Confirmed Fraud. Customer opened account, "
            "deposited Rs 50,000, then immediately transferred Rs 49,500 to "
            "an external account and disputed the original deposit. "
            "Cold start profile with only 1 prior transaction. Amount just "
            "below Rs 50,000 threshold. Outcome: Claim denied, account closed."
        ),
        "features": {
            "amount_z_score": 2.5,  "amount_vs_max": 1.8,
            "exceeds_daily_volume": 1, "is_large_amount": 0,
            "is_near_threshold": 1, "is_round_number": 0,
            "is_unusual_hour": 0, "hour_sin": 0.707, "hour_cos": 0.707,
            "is_new_recipient": 1, "transactions_last_1h": 1,
            "transactions_last_24h": 1, "is_velocity_burst": 0,
            "high_z_new_recipient": 1, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "first_party_fraud",
            "amount_range": "45000-50000",
            "signals": "cold_start,near_threshold,new_recipient,large_amount",
            "outcome": "confirmed_fraud",
            "severity": "HIGH",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
    {
        "id": "CASE-005-VELOCITY",
        "text": (
            "Velocity Attack — Confirmed Fraud. Compromised account used to "
            "execute 7 transactions in 30 minutes, all between Rs 5,000 and "
            "Rs 8,000 to different recipients. Each amount small enough to "
            "avoid per-transaction alerts, but velocity pattern was extreme. "
            "Total drained: Rs 42,000. Outcome: Account locked, partial recovery."
        ),
        "features": {
            "amount_z_score": 0.8,  "amount_vs_max": 0.7,
            "exceeds_daily_volume": 1, "is_large_amount": 0,
            "is_near_threshold": 0, "is_round_number": 1,
            "is_unusual_hour": 0, "hour_sin": 0.259, "hour_cos": 0.966,
            "is_new_recipient": 1, "transactions_last_1h": 7,
            "transactions_last_24h": 9, "is_velocity_burst": 1,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "velocity_attack",
            "amount_range": "5000-8000",
            "signals": "velocity_burst,multiple_new_recipients,round_numbers",
            "outcome": "confirmed_fraud",
            "severity": "HIGH",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
    {
        "id": "CASE-006-PHISHING",
        "text": (
            "Phishing-Induced Transfer — Confirmed Fraud. Customer deceived "
            "into making Rs 25,000 payment to a fraudulent recipient posing "
            "as a bank representative. Transaction occurred during normal hours "
            "(14:30) but to a completely new recipient. Amount z-score was 2.8. "
            "Outcome: STR filed, partial recovery through recipient bank."
        ),
        "features": {
            "amount_z_score": 2.8,  "amount_vs_max": 1.2,
            "exceeds_daily_volume": 0, "is_large_amount": 0,
            "is_near_threshold": 0, "is_round_number": 1,
            "is_unusual_hour": 0, "hour_sin": -0.707, "hour_cos": -0.707,
            "is_new_recipient": 1, "transactions_last_1h": 1,
            "transactions_last_24h": 2, "is_velocity_burst": 0,
            "high_z_new_recipient": 1, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "social_engineering",
            "amount_range": "20000-30000",
            "signals": "new_recipient,high_z_score",
            "outcome": "confirmed_fraud",
            "severity": "MEDIUM",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
    {
        "id": "CASE-007-BENIGN-HIGH",
        "text": (
            "Legitimate High-Value Transfer — False Positive. Established "
            "customer (85 prior transactions) made Rs 75,000 payment to a "
            "new recipient for property advance. Amount z-score was 1.9, "
            "within business hours. Customer confirmed the transaction when "
            "contacted. Outcome: Marked as false positive, no action taken."
        ),
        "features": {
            "amount_z_score": 1.9,  "amount_vs_max": 1.1,
            "exceeds_daily_volume": 0, "is_large_amount": 0,
            "is_near_threshold": 0, "is_round_number": 0,
            "is_unusual_hour": 0, "hour_sin": -0.5, "hour_cos": -0.866,
            "is_new_recipient": 1, "transactions_last_1h": 1,
            "transactions_last_24h": 2, "is_velocity_burst": 0,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "legitimate",
            "amount_range": "50000-100000",
            "signals": "new_recipient,moderate_z_score",
            "outcome": "false_positive",
            "severity": "LOW",
            "confirmed_risk_score": "15",   # [FIX-2]
        },
    },
    {
        "id": "CASE-008-BENIGN-BURST",
        "text": (
            "Legitimate Payment Burst — False Positive. Customer made 4 "
            "payments in 1 hour for monthly bill payments (electricity, "
            "internet, insurance, rent). All to known recipients, amounts "
            "consistent with history. Velocity burst triggered but all "
            "recipients previously transacted. Outcome: False positive."
        ),
        "features": {
            "amount_z_score": 0.2,  "amount_vs_max": 0.5,
            "exceeds_daily_volume": 0, "is_large_amount": 0,
            "is_near_threshold": 0, "is_round_number": 1,
            "is_unusual_hour": 0, "hour_sin": 0.866, "hour_cos": 0.5,
            "is_new_recipient": 0, "transactions_last_1h": 4,
            "transactions_last_24h": 5, "is_velocity_burst": 1,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "legitimate",
            "amount_range": "1000-15000",
            "signals": "velocity_burst_only",
            "outcome": "false_positive",
            "severity": "LOW",
            "confirmed_risk_score": "15",   # [FIX-2]
        },
    },
    {
        "id": "CASE-009-LATE-NIGHT-LEGIT",
        "text": (
            "Legitimate Late Night Transfer — False Positive. Customer with "
            "established late-night usage pattern (IT professional) made "
            "Rs 12,000 transfer at 01:30 AM to a known recipient. Despite "
            "late night flag, all other signals normal. Outcome: False positive, "
            "customer's usual hour window adjusted to include late hours."
        ),
        "features": {
            "amount_z_score": 0.4,  "amount_vs_max": 0.6,
            "exceeds_daily_volume": 0, "is_large_amount": 0,
            "is_near_threshold": 0, "is_round_number": 1,
            "is_unusual_hour": 1, "hour_sin": 0.383, "hour_cos": -0.924,
            "is_new_recipient": 0, "transactions_last_1h": 1,
            "transactions_last_24h": 2, "is_velocity_burst": 0,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "legitimate",
            "amount_range": "10000-15000",
            "signals": "late_night_only",
            "outcome": "false_positive",
            "severity": "LOW",
            "confirmed_risk_score": "15",   # [FIX-2]
        },
    },
    {
        "id": "CASE-010-LARGE-STRUCTURING",
        "text": (
            "Large-Scale Structuring — Confirmed Money Laundering. Over 2 weeks, "
            "customer made 15 transactions ranging from Rs 45,000 to Rs 49,900, "
            "all to different accounts. Each just below the Rs 50,000 enhanced "
            "due diligence threshold. Total moved: Rs 7,20,000. Pattern clearly "
            "showed deliberate threshold avoidance. Outcome: Account frozen, "
            "SAR filed, law enforcement referral made."
        ),
        "features": {
            "amount_z_score": 1.2,  "amount_vs_max": 0.9,
            "exceeds_daily_volume": 1, "is_large_amount": 0,
            "is_near_threshold": 1, "is_round_number": 0,
            "is_unusual_hour": 0, "hour_sin": 0.707, "hour_cos": 0.707,
            "is_new_recipient": 1, "transactions_last_1h": 2,
            "transactions_last_24h": 8, "is_velocity_burst": 0,
            "high_z_new_recipient": 0, "late_night_new_recipient": 0,
        },
        "metadata": {
            "pattern": "structuring",
            "amount_range": "45000-49999",
            "signals": "near_threshold,multiple_new_recipients,high_daily_frequency",
            "outcome": "confirmed_fraud",
            "severity": "CRITICAL",
            "confirmed_risk_score": "88",   # [FIX-2]
        },
    },
]


def ingest():
    """Seeds the L2_fraud_cases collection with historical fraud cases."""
    collection_name = COLLECTIONS['L2']

    ids       = [c['id'] for c in FRAUD_CASES]
    documents = [c['text'] for c in FRAUD_CASES]
    metadatas = [c['metadata'] for c in FRAUD_CASES]

    # [FIX-1] Generate embeddings using encode_features_for_l2 (128-d bootstrap
    # projection) — the same encoder used by rag_layer.py at query time.
    # Both stored vectors and query vectors are in the same projection space.
    embeddings = [encode_features_for_l2(c['features']) for c in FRAUD_CASES]

    upsert_vector_documents(collection_name, ids, embeddings, documents, metadatas)

    count = collection_count(collection_name)
    print(f"✅ L2_fraud_cases seeded with {count} historical cases.")


if __name__ == '__main__':
    ingest()
