"""
test_cla.py
───────────
Unit tests for CLA Agent (Citation & Legal Archive Agent).

Tests:
  - STR auto-filing when score >= 85
  - STR pending approval when 70 <= score < 85
  - CTR auto-filing for high-value transactions (>= 200k)
  - Status determination logic based on RAA score
"""

import unittest
from unittest.mock import patch, MagicMock
import json


class TestProcessCaseSTRAutoFile(unittest.TestCase):
    """Tests for CLA agent processing STR with AUTO_FILED status."""

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_str')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_str_auto_file_high_score(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_str,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """STR case with final_raa_score >= 85 should AUTO_FILE."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = {
            'case_id': 'CASE-001',
            'alert_id': 'ALERT-001',
            'customer_id': 'CUST-001',
            'priority': 'P1',
            'created_at': '2026-03-22 10:00:00'
        }

        mock_get_alert.return_value = {
            'alert_id': 'ALERT-001',
            'transaction_id': 'TXN-001',
            'final_raa_score': 92.5,
            'rag_citations': json.dumps([{'id': 'citation-1', 'source': 'L1_regulatory'}]),
            'raa_citations': None,
            'pra_reg_citations': None
        }

        mock_get_txn.return_value = {
            'transaction_id': 'TXN-001',
            'amount': 50000,
            'timestamp': '2026-03-22 10:00:00'
        }

        mock_get_customer.return_value = {
            'customer_id': 'CUST-001',
            'name': 'John Doe',
            'account_number': 'ACC-001'
        }

        mock_archive_citations.return_value = ['citation-1']
        mock_assemble_str.return_value = {
            'filing_id': 'STR-2026-001',
            'case_id': 'CASE-001',
            'narrative': 'Suspicious transaction detected',
            'investigation_note': 'Auto-generated by CLA'
        }
        mock_insert_filing.return_value = True
        mock_insert_archive.return_value = True

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-001')

        self.assertEqual(filing_id, 'STR-2026-001')
        mock_get_case.assert_called_once_with('CASE-001')

        filing_call_args = mock_insert_filing.call_args
        self.assertEqual(filing_call_args[1]['status'], 'AUTO_FILED')
        self.assertEqual(filing_call_args[1]['filing_type'], 'STR')
        mock_mark_consumed.assert_called_once_with('CASE-001')

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_str')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_missing_case_data_returns_none(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_str,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """If case not found, process_case should return None."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = None

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-NOTFOUND')

        self.assertIsNone(filing_id)
        mock_get_case.assert_called_once_with('CASE-NOTFOUND')
        mock_get_alert.assert_not_called()
        mock_mark_consumed.assert_not_called()


class TestProcessCaseSTRPendingApproval(unittest.TestCase):
    """Tests for CLA agent processing STR with PENDING_APPROVAL status."""

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_str')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_str_pending_approval_mid_score(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_str,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """STR case with 70 <= final_raa_score < 85 should PENDING_APPROVAL."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = {
            'case_id': 'CASE-002',
            'alert_id': 'ALERT-002',
            'customer_id': 'CUST-002',
            'priority': 'P2'
        }

        mock_get_alert.return_value = {
            'alert_id': 'ALERT-002',
            'transaction_id': 'TXN-002',
            'final_raa_score': 77.0,
            'rag_citations': None,
            'raa_citations': json.dumps([{'id': 'citation-2', 'source': 'L2_fraud_cases'}]),
            'pra_reg_citations': None
        }

        mock_get_txn.return_value = {
            'transaction_id': 'TXN-002',
            'amount': 75000,
            'timestamp': '2026-03-22 11:00:00'
        }

        mock_get_customer.return_value = {
            'customer_id': 'CUST-002',
            'name': 'Jane Smith',
            'account_number': 'ACC-002'
        }

        mock_archive_citations.return_value = ['citation-2']
        mock_assemble_str.return_value = {
            'filing_id': 'STR-2026-002',
            'case_id': 'CASE-002',
            'narrative': 'Pattern of unusual transactions',
            'investigation_note': 'Requires compliance review'
        }
        mock_insert_filing.return_value = True
        mock_insert_archive.return_value = True

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-002')

        self.assertEqual(filing_id, 'STR-2026-002')
        filing_call_args = mock_insert_filing.call_args
        self.assertEqual(filing_call_args[1]['status'], 'PENDING_APPROVAL')
        self.assertEqual(filing_call_args[1]['filing_type'], 'STR')
        mock_mark_consumed.assert_called_once_with('CASE-002')

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_str')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_str_rejected_low_score(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_str,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """STR case with final_raa_score < 70 should be REJECTED."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = {
            'case_id': 'CASE-003',
            'alert_id': 'ALERT-003',
            'customer_id': 'CUST-003',
            'priority': 'P3'
        }

        mock_get_alert.return_value = {
            'alert_id': 'ALERT-003',
            'transaction_id': 'TXN-003',
            'final_raa_score': 55.0,
            'rag_citations': None,
            'raa_citations': None,
            'pra_reg_citations': None
        }

        mock_get_txn.return_value = {
            'transaction_id': 'TXN-003',
            'amount': 30000,
            'timestamp': '2026-03-22 12:00:00'
        }

        mock_get_customer.return_value = {
            'customer_id': 'CUST-003',
            'name': 'Bob Johnson',
            'account_number': 'ACC-003'
        }

        mock_archive_citations.return_value = []
        mock_assemble_str.return_value = {
            'filing_id': 'STR-2026-003',
            'case_id': 'CASE-003',
            'narrative': 'Low-risk transaction',
            'investigation_note': 'Below threshold'
        }
        mock_insert_filing.return_value = True
        mock_insert_archive.return_value = True

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-003')

        self.assertEqual(filing_id, 'STR-2026-003')
        filing_call_args = mock_insert_filing.call_args
        self.assertEqual(filing_call_args[1]['status'], 'REJECTED')
        mock_mark_consumed.assert_called_once_with('CASE-003')


class TestProcessCaseCTRAutoFile(unittest.TestCase):
    """Tests for CLA agent processing CTR (high-value transactions) with AUTO_FILED status."""

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_ctr')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_ctr_high_value_auto_file(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_ctr,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """High-value transaction (>= 200k) should trigger CTR with AUTO_FILED."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = {
            'case_id': 'CASE-004',
            'alert_id': 'ALERT-004',
            'customer_id': 'CUST-004',
            'priority': 'P1'
        }

        mock_get_alert.return_value = {
            'alert_id': 'ALERT-004',
            'transaction_id': 'TXN-004',
            'final_raa_score': 45.0,
            'rag_citations': None,
            'raa_citations': None,
            'pra_reg_citations': None
        }

        # High-value transaction (>= 200k)
        mock_get_txn.return_value = {
            'transaction_id': 'TXN-004',
            'amount': 250000.00,
            'timestamp': '2026-03-22 13:00:00'
        }

        mock_get_customer.return_value = {
            'customer_id': 'CUST-004',
            'name': 'Alice Brown',
            'account_number': 'ACC-004'
        }

        mock_archive_citations.return_value = []
        mock_assemble_ctr.return_value = {
            'filing_id': 'CTR-2026-001',
            'case_id': 'CASE-004',
            'narrative': 'High-value international transfer',
            'investigation_note': 'CTR auto-filed by CLA'
        }
        mock_insert_filing.return_value = True
        mock_insert_archive.return_value = True

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-004')

        self.assertEqual(filing_id, 'CTR-2026-001')
        filing_call_args = mock_insert_filing.call_args
        self.assertEqual(filing_call_args[1]['filing_type'], 'CTR')
        self.assertEqual(filing_call_args[1]['status'], 'AUTO_FILED')
        self.assertEqual(filing_call_args[1]['amount'], 250000.00)
        mock_mark_consumed.assert_called_once_with('CASE-004')

    @patch('et_service.cla.cla_agent.mark_case_consumed')
    @patch('et_service.cla.cla_agent.insert_archive')
    @patch('et_service.cla.cla_agent.insert_regulatory_filing')
    @patch('et_service.cla.cla_agent.assemble_str')
    @patch('et_service.cla.cla_agent.archive_from_alert_citations')
    @patch('et_service.cla.cla_agent.get_customer_by_id')
    @patch('et_service.cla.cla_agent.get_transaction_by_id')
    @patch('et_service.cla.cla_agent.get_alert_by_id')
    @patch('et_service.cla.cla_agent.get_case_by_id')
    def test_process_case_below_ctr_threshold_uses_str(
        self,
        mock_get_case,
        mock_get_alert,
        mock_get_txn,
        mock_get_customer,
        mock_archive_citations,
        mock_assemble_str,
        mock_insert_filing,
        mock_insert_archive,
        mock_mark_consumed
    ):
        """Low-value transaction (< 200k) should use STR, not CTR."""
        from et_service.cla.cla_agent import CLAAgent

        mock_get_case.return_value = {
            'case_id': 'CASE-005',
            'alert_id': 'ALERT-005',
            'customer_id': 'CUST-005',
            'priority': 'P3'
        }

        mock_get_alert.return_value = {
            'alert_id': 'ALERT-005',
            'transaction_id': 'TXN-005',
            'final_raa_score': 75.0,
            'rag_citations': None,
            'raa_citations': None,
            'pra_reg_citations': None
        }

        # Below CTR threshold
        mock_get_txn.return_value = {
            'transaction_id': 'TXN-005',
            'amount': 150000.00,
            'timestamp': '2026-03-22 14:00:00'
        }

        mock_get_customer.return_value = {
            'customer_id': 'CUST-005',
            'name': 'Charlie Davis',
            'account_number': 'ACC-005'
        }

        mock_archive_citations.return_value = []
        mock_assemble_str.return_value = {
            'filing_id': 'STR-2026-005',
            'case_id': 'CASE-005',
            'narrative': 'Unusual beneficiary activity',
            'investigation_note': 'Requires approval'
        }
        mock_insert_filing.return_value = True
        mock_insert_archive.return_value = True

        agent = CLAAgent(poll_interval_ms=500)
        filing_id = agent.process_case('CASE-005')

        # Should be STR, not CTR
        filing_call_args = mock_insert_filing.call_args
        self.assertEqual(filing_call_args[1]['filing_type'], 'STR')
        self.assertEqual(filing_call_args[1]['status'], 'PENDING_APPROVAL')
        mock_mark_consumed.assert_called_once_with('CASE-005')


class TestDetermineStrStatus(unittest.TestCase):
    """Tests for CLA agent's status determination logic based on RAA score."""

    def test_determine_str_status_auto_file_high_score(self):
        """Score >= 85 should return AUTO_FILED."""
        from et_service.cla.cla_agent import CLAAgent

        agent = CLAAgent(poll_interval_ms=500)
        self.assertEqual(agent._determine_str_status(85.0), 'AUTO_FILED')
        self.assertEqual(agent._determine_str_status(95.0), 'AUTO_FILED')
        self.assertEqual(agent._determine_str_status(100.0), 'AUTO_FILED')

    def test_determine_str_status_pending_approval_mid_range(self):
        """70 <= score < 85 should return PENDING_APPROVAL."""
        from et_service.cla.cla_agent import CLAAgent

        agent = CLAAgent(poll_interval_ms=500)
        self.assertEqual(agent._determine_str_status(70.0), 'PENDING_APPROVAL')
        self.assertEqual(agent._determine_str_status(77.5), 'PENDING_APPROVAL')
        self.assertEqual(agent._determine_str_status(84.9), 'PENDING_APPROVAL')

    def test_determine_str_status_rejected_low_score(self):
        """Score < 70 should return REJECTED."""
        from et_service.cla.cla_agent import CLAAgent

        agent = CLAAgent(poll_interval_ms=500)
        self.assertEqual(agent._determine_str_status(69.9), 'REJECTED')
        self.assertEqual(agent._determine_str_status(50.0), 'REJECTED')
        self.assertEqual(agent._determine_str_status(0.0), 'REJECTED')

    def test_determine_str_status_boundary_conditions(self):
        """Test boundary conditions precisely."""
        from et_service.cla.cla_agent import CLAAgent

        agent = CLAAgent(poll_interval_ms=500)
        self.assertEqual(agent._determine_str_status(70.0), 'PENDING_APPROVAL')
        self.assertEqual(agent._determine_str_status(85.0), 'AUTO_FILED')
        self.assertEqual(agent._determine_str_status(69.99), 'REJECTED')
        self.assertEqual(agent._determine_str_status(84.99), 'PENDING_APPROVAL')
        self.assertEqual(agent._determine_str_status(70.01), 'PENDING_APPROVAL')
        self.assertEqual(agent._determine_str_status(85.01), 'AUTO_FILED')


if __name__ == '__main__':
    unittest.main()
